# 1) Basic - Polynomial

In [1]:
from numpy import poly1d
p = poly1d([3,6,8]) # pass list as a argument.
print(p)

   2
3 x + 6 x + 8


In [2]:
print(p*p) # multiplication of 2 polynomial.

   4      3      2
9 x + 36 x + 84 x + 96 x + 64


In [3]:
# Root of Perticular polynomial is:
p.r #it give array of root.

array([-1.+1.29099445j, -1.-1.29099445j])

In [4]:
# Coefficients of p
p # it give us only coefficient.

poly1d([3, 6, 8])

In [5]:
print(p)
p1 = poly1d([1,2,3],variable="p") # equation with variable as p.
print(p1)

   2
3 x + 6 x + 8
   2
1 p + 2 p + 3


In [6]:
# Integration of a Polynomial

print(p.integ(k=6)) # k = indefinite integration constant here k is like constant in integration.

   3     2
1 x + 3 x + 8 x + 6


In [7]:
# Differentiation of a Polynomial.

print(p.deriv())

 
6 x + 6


# 2) Special Function(import scipy.special)

In [8]:
import scipy.special

In [9]:
import numpy as np
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# For cube root of each element in array.
scipy.special.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [11]:
# Exponent of 10 (exp10()) 
x = 3
scipy.special.exp10(x)

1000.0

In [12]:
# Exponent of 2 (exp2())
x = 3
scipy.special.exp2(x)

8.0

In [13]:
# Degree to  Radian (radian(d,m,s))
d = 30 # degree
m = 10 # minute
s = 50 # seconds
scipy.special.radian(d,m,s)



0.5267500645255109

In [14]:
# Trignometric Functions (in degrees)
print("sine of 30 degrees =" , scipy.special.sindg(30))
print("Cosine of 30 degrees =" , scipy.special.cosdg(30))
print("Tangent of 45 degrees =" , scipy.special.tandg(45))

sine of 30 degrees = 0.49999999999999994
Cosine of 30 degrees = 0.8660254037844387
Tangent of 45 degrees = 1.0


In [15]:
# Permutations 

scipy.special.perm(5,2)  # we know 5P2 is 20. 

20.0

In [16]:
# Combination

scipy.special.comb(5,2) # we know 5C2 is 10.


10.0

# 3) Integration (import scipy.integrate)

In [17]:
import scipy.integrate

In [18]:
def f(x):
    return x**2
f(3)


9

In [19]:
f = lambda x : x**2 # in lambda  function first we give argument then we give what will it do or return.
f(3)
    

9

In [20]:
g = lambda x,y : x*y
g(2,3)

6

In [21]:
h = lambda x,y : x**2 + 2*x*y + y**2 # (x+y)^2
h(1,2)

9

In [22]:
# scipy.inregrate.quad(function,lower_limit,upper_limit)
f = lambda x : x*2 # function is 2x.
i = scipy.integrate.quad(f,1,2) # quad means simple integration. Single integration
i


(3.0, 3.3306690738754696e-14)

In [23]:
from numpy import exp
f = lambda x : exp(-x**3)
i = scipy.integrate.quad(f,1,4)
i 

(0.08546832942957776, 2.1640276156712023e-12)

In [24]:
# Double Integration (used for area under curve)

#scipy.integrate.dblquad(func,lower_limit,upper_limit,func2,func3)
area = scipy.integrate.dblquad(lambda x,y :x*y , 0 , 0.5 , lambda x: 0, lambda y : 1-2*y)
area

(0.010416666666666668, 4.101620128472366e-16)

# 4) Linear Algebra (import scipy.linalg)

In [25]:
from scipy import linalg


In [26]:
import numpy as np


In [27]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [28]:
# Determinant of matrix
linalg.det(a1)

-2.0

**Compute pivoted LU decompostion of a matrix**

In [29]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
P,L,U = linalg.lu(A) # it return three matrix and we store these matrixs in P ,L and U.

In [31]:
P # It is permutation matrix

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [32]:
L # lower triangular matrix with unit diagonal elements.

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [33]:
U # upper triangular matrix.

array([[7.        , 8.        , 9.        ],
       [0.        , 0.85714286, 1.71428571],
       [0.        , 0.        , 0.        ]])

**We Can find out the eigenvector and eigenvalues of a matrix**

In [34]:
EV,EW = linalg.eig(A) # it generate 2 array one for eigen values and other for eigen vector.

In [35]:
# Eigen Values
EV

array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -1.30367773e-15+0.j])

In [36]:
# Eigen vector
EW

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

**Solving systems of linear equations can also be done:**

In [37]:
A[2,2] = 8 
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [38]:
B = np.array([[2],[3],[5]])
B

array([[2],
       [3],
       [5]])

In [39]:
# solve Linear Equation using Matrix (AX = B)
# linalg.solve()

X = linalg.solve(A,B)

In [40]:
X 

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

**Inverse of a matrix**

In [41]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [42]:
#Inverse : linalg.inv()
linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [44]:
#Cross Check
# A * inv(A) = I
I = A.dot(linalg.inv(A))
print(np.around(I)) # it give integer value or it around the value to a integer.

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


# 5) Fourier Transform(import scipy.fftpack)

**The Fourier Transform shows that any waveform can be re-written as the sum of sinusoidal functions**

**fft : Fast Fourier Transformation**

**ifft : Inverse Fast Fourier Transformation**

In [45]:
import scipy.fftpack

In [47]:
import numpy as np 
a = np.array([1,5,6,14,25,40])
a

array([ 1,  5,  6, 14, 25, 40])

In [48]:
# Fourier Transformation
y = scipy.fftpack.fft(a)
y

array([ 91. -0.j        ,  -6.+46.7653718j , -23.+13.85640646j,
       -27. -0.j        , -23.-13.85640646j,  -6.-46.7653718j ])

In [50]:
# Inverse Fourier Transformation
invy = scipy.fftpack.ifft(a)
invy

array([15.16666667-0.j        , -1.        -7.79422863j,
       -3.83333333-2.30940108j, -4.5       -0.j        ,
       -3.83333333+2.30940108j, -1.        +7.79422863j])

In [52]:
# Cross Verifiaction
i = scipy.fftpack.fft(invy)
print(i)
a

[ 1.+0.j  5.+0.j  6.-0.j 14.+0.j 25.+0.j 40.+0.j]


array([ 1,  5,  6, 14, 25, 40])

# 6) Interpolation (import scipy.interpolate)

**Interpolation is a type of estimation , a method of constructing new data points whithin the range of a discrete set of known data points**

In [54]:
from scipy.interpolate import interp1d
import numpy as np


# 7) Statistics (import scipy.stats)


In [55]:
from scipy.stats import norm

In [56]:
# this gives you a numpy array with 500 elements
# ranomely valued according to the standard normal distribution (mean = 0 ,std =1)
x_norm = norm.rvs(size = 500)            # rvs --> Random Variates
print(type(x_norm))

<class 'numpy.ndarray'>


In [65]:
x_norm.mean() , x_norm.std() , x_norm.var()

(-0.030194342847694747, 0.9982850726687306, 0.9965730863132127)

In [66]:
# CDF : Continous Distribution Function
z = np.array([1,-1,0,1,3,4,-2,6])
norm.cdf(z)

array([0.84134475, 0.15865525, 0.5       , 0.84134475, 0.9986501 ,
       0.99996833, 0.02275013, 1.        ])

In [68]:
# PPF : Percent point function
# It is reverse of CDF
norm.ppf(0.5) # it return the element of array whose cdf is 0.5 .

0.0

In [69]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x.max(),x.min(),x.mean(),x.var(),sep=",")

9,1,5.0,6.666666666666667


In [71]:
# Geometric Mean
from scipy.stats.mstats import gmean
g = gmean([1,2,4])
print("Geometric Mean is :" , g)



Geometric Mean is : 2.0


In [72]:
# Harmonic Mean
from scipy.stats.mstats import hmean
h = hmean([1,5,20])
print("Harmonic Mean is :", h)

Harmonic Mean is : 2.4


In [75]:
# Mode
from scipy import stats
arr1 = np.array([1,3,15,11,9,9,9,3])
print("Arithmetic mode is :", stats.mode(arr1))


Arithmetic mode is : ModeResult(mode=array([9]), count=array([3]))


In [76]:
#Z-Score
arr1 = [20,2,7,1,25]
print("Z-score for arr1",stats.zscore(arr1))

Z-score for arr1 [ 0.92435403 -0.92435403 -0.41082402 -1.02706004  1.43788405]


In [77]:
scipy.constants.find() # this will give us constants which are used in scientific calculations

['Angstrom star',
 'Avogadro constant',
 'Bohr magneton',
 'Bohr magneton in Hz/T',
 'Bohr magneton in K/T',
 'Bohr magneton in eV/T',
 'Bohr magneton in inverse meter per tesla',
 'Bohr radius',
 'Boltzmann constant',
 'Boltzmann constant in Hz/K',
 'Boltzmann constant in eV/K',
 'Boltzmann constant in inverse meter per kelvin',
 'Compton wavelength',
 'Cu x unit',
 'Faraday constant',
 'Fermi coupling constant',
 'Hartree energy',
 'Hartree energy in eV',
 'Josephson constant',
 'Loschmidt constant (273.15 K, 100 kPa)',
 'Loschmidt constant (273.15 K, 101.325 kPa)',
 'Mo x unit',
 'Newtonian constant of gravitation',
 'Newtonian constant of gravitation over h-bar c',
 'Planck constant',
 'Planck constant in eV/Hz',
 'Planck length',
 'Planck mass',
 'Planck mass energy equivalent in GeV',
 'Planck temperature',
 'Planck time',
 'Rydberg constant',
 'Rydberg constant times c in Hz',
 'Rydberg constant times hc in J',
 'Rydberg constant times hc in eV',
 'Sackur-Tetrode constant (1 K, 