# 1) Basic - Polynomial

In [4]:
from numpy import poly1d
p = poly1d([3,6,8]) # pass list as a argument.
print(p)

   2
3 x + 6 x + 8


In [5]:
print(p*p) # multiplication of 2 polynomial.

   4      3      2
9 x + 36 x + 84 x + 96 x + 64


In [6]:
# Root of Perticular polynomial is:
p.r #it give array of root.

array([-1.+1.29099445j, -1.-1.29099445j])

In [8]:
# Coefficients of p
p # it give us only coefficient.

poly1d([3, 6, 8])

In [9]:
print(p)
p1 = poly1d([1,2,3],variable="p") # equation with variable as p.
print(p1)

   2
3 x + 6 x + 8
   2
1 p + 2 p + 3


In [10]:
# Integration of a Polynomial

print(p.integ(k=6)) # k = indefinite integration constant here k is like constant in integration.

   3     2
1 x + 3 x + 8 x + 6


In [11]:
# Differentiation of a Polynomial.

print(p.deriv())

 
6 x + 6


# 2) Special Function(import scipy.special)

In [12]:
import scipy.special

In [13]:
import numpy as np
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# For cube root of each element in array.
scipy.special.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [15]:
# Exponent of 10 (exp10()) 
x = 3
scipy.special.exp10(x)

1000.0

In [16]:
# Exponent of 2 (exp2())
x = 3
scipy.special.exp2(x)

8.0

In [17]:
# Degree to  Radian (radian(d,m,s))
d = 30 # degree
m = 10 # minute
s = 50 # seconds
scipy.special.radian(d,m,s)



0.5267500645255109

In [19]:
# Trignometric Functions (in degrees)
print("sine of 30 degrees =" , scipy.special.sindg(30))
print("Cosine of 30 degrees =" , scipy.special.cosdg(30))
print("Tangent of 45 degrees =" , scipy.special.tandg(45))

sine of 30 degrees = 0.49999999999999994
Cosine of 30 degrees = 0.8660254037844387
Tangent of 45 degrees = 1.0


In [21]:
# Permutations 

scipy.special.perm(5,2)  # we know 5P2 is 20. 

20.0

In [22]:
# Combination

scipy.special.comb(5,2) # we know 5C2 is 10.


10.0

# 3) Integration (import scipy.integrate)

In [23]:
import scipy.integrate

In [24]:
def f(x):
    return x**2
f(3)


9

In [25]:
f = lambda x : x**2 # in lambda  function first we give argument then we give what will it do or return.
f(3)
    

9

In [26]:
g = lambda x,y : x*y
g(2,3)

6

In [27]:
h = lambda x,y : x**2 + 2*x*y + y**2 # (x+y)^2
h(1,2)

9

In [30]:
# scipy.inregrate.quad(function,lower_limit,upper_limit)
f = lambda x : x*2 # function is 2x.
i = scipy.integrate.quad(f,1,2) # quad means simple integration. Single integration
i


(3.0, 3.3306690738754696e-14)

In [31]:
from numpy import exp
f = lambda x : exp(-x**3)
i = scipy.integrate.quad(f,1,4)
i 

(0.08546832942957776, 2.1640276156712023e-12)

In [32]:
# Double Integration (used for area under curve)

#scipy.integrate.dblquad(func,lower_limit,upper_limit,func2,func3)
area = scipy.integrate.dblquad(lambda x,y :x*y , 0 , 0.5 , lambda x: 0, lambda y : 1-2*y)
area

(0.010416666666666668, 4.101620128472366e-16)

# 4) Linear Algebra (import scipy.linalg)

In [34]:
from scipy import linalg


In [35]:
import numpy as np


In [37]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [38]:
# Determinant of matrix
linalg.det(a1)

-2.0

**Compute pivoted LU decompostion of a matrix**

In [40]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
P,L,U = linalg.lu(A) # it return three matrix and we store these matrixs in P ,L and U.

In [42]:
P # It is permutation matrix

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [43]:
L # lower triangular matrix with unit diagonal elements.

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [44]:
U # upper triangular matrix.

array([[7.        , 8.        , 9.        ],
       [0.        , 0.85714286, 1.71428571],
       [0.        , 0.        , 0.        ]])

**We Can find out the eigenvector and eigenvalues of a matrix**

In [45]:
EV,EW = linalg.eig(A) # it generate 2 array one for eigen values and other for eigen vector.

In [47]:
# Eigen Values
EV

array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -1.30367773e-15+0.j])

In [48]:
# Eigen vector
EW

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

**Solving systems of linear equations can also be done:**

In [57]:
A[2,2] = 8 
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [53]:
B = np.array([[2],[3],[5]])
B

array([[2],
       [3],
       [5]])

In [58]:
# solve Linear Equation using Matrix (AX = B)
# linalg.solve()

X = linalg.solve(A,B)

In [59]:
X 

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])