# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,25,7]],np.int32)

In [3]:
myarr[0,1] # It is a NumPy array from python list.

6

In [4]:
myarr.shape # it give shape of array means no. of rows and no. of columns.

(1, 4)

In [5]:
myarr.dtype # it give its data type.

dtype('int32')

In [6]:
myarr[0,1] = 735

In [7]:
myarr

array([[  3, 735,  25,   7]])

# Array creation: Conversion from other Python structures.

In [9]:
listarray = np.array([[1,2,3],[5,6,7],[4,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [4, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.size

9

In [13]:
listarray.shape

(3, 3)

In [14]:
np.array({34,23,45})

array({34, 45, 23}, dtype=object)

In [15]:
zeros = np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.shape

(2, 5)

In [19]:
rng = np.arange(15) #  it create a numpy array, till n-1 .

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1,5,12) # it give from 1 to 5 linearly spaced 12 elements.

In [22]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
emp = np.empty((4,6)) # it give a array with random values you can assign your own values using indexing.

In [24]:
emp

array([[1.05226939e-311, 1.05227265e-311, 1.05227265e-311,
        1.05227268e-311, 1.05227268e-311, 1.05227268e-311],
       [1.05227268e-311, 1.05227268e-311, 1.05227268e-311,
        1.05227268e-311, 1.05227268e-311, 1.05227268e-311],
       [1.05227268e-311, 1.05227268e-311, 1.05227268e-311,
        1.05227268e-311, 1.05227268e-311, 1.05227268e-311],
       [1.05227268e-311, 1.05227268e-311, 1.05227268e-311,
        1.05227268e-311, 1.05227268e-311, 1.05227268e-311]])

In [25]:
emp_like = np.empty_like(lspace)

In [26]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [27]:
ide = np.identity(45) # it give a identity matrix of 45*45.

In [28]:
ide.shape

(45, 45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr = arr.reshape(9,11) # it reshape arr by = 9*11 ==>99

In [1]:
arr

NameError: name 'arr' is not defined

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [42]:
arr = arr.ravel() # it make it 1D aaray.

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

In [45]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [46]:
ar = np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis =0) # axis 0 is row so it add each row 

array([12,  8,  9])

In [49]:
ar.sum(axis=1) # axis 1 is column so it add each column.

array([ 6, 15,  8])

In [50]:
ar.T # to transepose an array  we use this.

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
ar.flat # it give a iterator.

In [52]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [53]:
ar.ndim # it tell no. of dimensions

2

In [54]:
ar.nbytes # total bytes consums by your elements

36

In [55]:
one = np.array([1,3,4,634,2])

In [56]:
one.argmax() # it give index where we have max element.

3

In [57]:
one.argmin() # it give index where we have min element.

0

In [58]:
one.argsort() # it give list of index if we place our element according to this list we get a sorted array.

array([0, 4, 1, 2, 3], dtype=int64)

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.argmin()

8

In [61]:
ar.argmax()

6

In [62]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [63]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [64]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

# Matrix Operation in NumPy

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar2 = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [71]:
ar + ar2 

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [74]:
x = [324,34] + [45,67]

In [75]:
x

[324, 34, 45, 67]

In [76]:
ar*ar2 # it give element wise multiplication

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [77]:
np.sqrt(ar) # it give element wise square root.

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [78]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [79]:
print(ar)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


In [80]:
ar.sum

<function ndarray.sum>

In [81]:
ar.sum()

29

In [82]:
ar.min()

0

In [83]:
ar.max()

7

In [85]:
np.where(ar>5) # it return tuple of arrays index where we get value greater then 5.

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [86]:
np.count_nonzero(ar)

8

In [88]:
np.nonzero(ar) # it give index of elements where they are non zero.

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [89]:
ar[1,2] = 0 

In [90]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [91]:
import sys

In [101]:
py_ar = [0,4,55,1]

In [102]:
np_ar = np.array(py_ar)

In [103]:
sys.getsizeof(1)*len(py_ar)

112

In [3]:
np_ar.itemsize * np_ar.size 

NameError: name 'np_ar' is not defined

In [2]:
np_ar.tolist() # it give python list of numpy array.

NameError: name 'np_ar' is not defined

In [4]:
ar

NameError: name 'ar' is not defined